### ISSUE TITLE
Undefined array key 0 in /var/www/html/index.php on line 56

### ISSUE THREAD

**Issue by rauschgiftengel** [Palleri/localca-buildv2#5]
Hi :)
found your app mentioned at reddit and want to give it a try. Definately looks promising. 

But getting the same error on every single approach:

Maybe you have an idea how to fix that ? 
![ca](https://user-images.githubusercontent.com/59368208/213916245-170eb63e-7f94-46c0-a992-95b060de866c.jpg)

**Comment by Palleri** [comment]
> Hi :) found your app mentioned at reddit and want to give it a try. Definately looks promising.
> 
> But getting the same error on every single approach:
> 
> Maybe you have an idea how to fix that ? ![ca](https://user-images.githubusercontent.com/59368208/213916245-170eb63e-7f94-46c0-a992-95b060de866c.jpg)

Hi, I recently discovered this issue myself. I pushed a new update regarding this issue.I think it is fixed on main branch.If not I will try to fix this during this week.

When did you update?
If main isnt working try to use the branch 2.3.

Thank you for letting me know!

**Comment by Palleri** [comment]
No answer
